apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: merchant-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant-api
  template:
    metadata:
      labels:
        app: merchant-api
    spec:
      containers:
        - name: merchant-api
          image: registry.gitlab.com/otis-team/backend/api/merchant:latest
          imagePullPolicy: Always
          command: [
            "./api-merchant",
            "--server_name=go.micro.api.merchant",
            "--server_address=0.0.0.0:8080",
            "--runtime=kubernetes"
          ]
          env:
            - name: MICRO_SELECTOR
              value: "static"
            - name: MICRO_REGISTRY
              value: "etcd"
            - name: MICRO_REGISTRY_ADDRESS
              value: "http://etcd-cluster-client"
          ports:
            - containerPort: 8080
              name: mapi-port
            - containerPort: 53
              name: dnsport

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  namespace: default
#  name: merchant-api
#  labels:
#    app: merchant-api
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      app: merchant-api
#  strategy:
#    type: RollingUpdate
#    rollingUpdate:
#      maxSurge: 1
#      maxUnavailable: 33%
#  template:
#    metadata:
#      labels:
#        app: merchant-api
#    spec:
#      imagePullSecrets:
#        - name: my-registry
#      containers:
#        - name: merchant-api
#          image: registry.gitlab.com/otis-team/backend/api/merchant:latest
#          command: [
#            "./api-merchant",
#          ]
#          ports:
#            - containerPort: 8080
#              name: mapi-port
#          env:
#            - name: MICRO_SERVER_ADDRESS
#              value: "0.0.0.0:8070"
##            - name: MICRO_BROKER
##              value: "nats"
##            - name: MICRO_BROKER_ADDRESS
##              value: "nats-cluster"
#            - name: MICRO_REGISTRY
#              value: "etcd"
#            - name: MICRO_REGISTRY_ADDRESS
#              value: "etcd-cluster-client"
#        - name: health
#          command: [
#            "/health",
#            "--health_address=0.0.0.0:8081",
#            "--server_name=merchant-api",
#            "--server_address=0.0.0.0:80"
#          ]
#          image: microhq/health
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 8081
#            initialDelaySeconds: 3
#            periodSeconds: 3
