apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: merchant-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant-api
  template:
    metadata:
      labels:
        app: merchant-api
    spec:
      containers:
        - name: merchant-api
          image: registry.gitlab.com/otis-team/backend/api/merchant:latest
          imagePullPolicy: Always
          command: [
            "./api-merchant",
            "--server_address=0.0.0.0:8080",
            "--runtime=kubernetes"
          ]
          env:
            - name: MICRO_SELECTOR
              value: "static"
            - name: MICRO_REGISTRY
              value: "etcd"
            - name: MICRO_REGISTRY_ADDRESS
              value: "etcd-cluster-client"
          ports:
            - containerPort: 8080
              name: mapi-port
            - containerPort: 53
              name: dnsport
