// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/general-merchant.proto

package generalmerchant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GeneralMerchant struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Locations            []string `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	ApiTags              []string `protobuf:"bytes,4,rep,name=api_tags,json=apiTags,proto3" json:"api_tags,omitempty"`
	ScrapeTags           []string `protobuf:"bytes,5,rep,name=scrape_tags,json=scrapeTags,proto3" json:"scrape_tags,omitempty"`
	Sector               string   `protobuf:"bytes,6,opt,name=sector,proto3" json:"sector,omitempty"`
	Size                 string   `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	ExpenseBand          string   `protobuf:"bytes,12,opt,name=expenseBand,proto3" json:"expenseBand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralMerchant) Reset()         { *m = GeneralMerchant{} }
func (m *GeneralMerchant) String() string { return proto.CompactTextString(m) }
func (*GeneralMerchant) ProtoMessage()    {}
func (*GeneralMerchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_da8993875e4e54cb, []int{0}
}

func (m *GeneralMerchant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralMerchant.Unmarshal(m, b)
}
func (m *GeneralMerchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralMerchant.Marshal(b, m, deterministic)
}
func (m *GeneralMerchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralMerchant.Merge(m, src)
}
func (m *GeneralMerchant) XXX_Size() int {
	return xxx_messageInfo_GeneralMerchant.Size(m)
}
func (m *GeneralMerchant) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralMerchant.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralMerchant proto.InternalMessageInfo

func (m *GeneralMerchant) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeneralMerchant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GeneralMerchant) GetLocations() []string {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *GeneralMerchant) GetApiTags() []string {
	if m != nil {
		return m.ApiTags
	}
	return nil
}

func (m *GeneralMerchant) GetScrapeTags() []string {
	if m != nil {
		return m.ScrapeTags
	}
	return nil
}

func (m *GeneralMerchant) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

func (m *GeneralMerchant) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *GeneralMerchant) GetExpenseBand() string {
	if m != nil {
		return m.ExpenseBand
	}
	return ""
}

type GeneralMerchants struct {
	GeneralMerchants     []*GeneralMerchant `protobuf:"bytes,1,rep,name=generalMerchants,proto3" json:"generalMerchants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GeneralMerchants) Reset()         { *m = GeneralMerchants{} }
func (m *GeneralMerchants) String() string { return proto.CompactTextString(m) }
func (*GeneralMerchants) ProtoMessage()    {}
func (*GeneralMerchants) Descriptor() ([]byte, []int) {
	return fileDescriptor_da8993875e4e54cb, []int{1}
}

func (m *GeneralMerchants) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralMerchants.Unmarshal(m, b)
}
func (m *GeneralMerchants) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralMerchants.Marshal(b, m, deterministic)
}
func (m *GeneralMerchants) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralMerchants.Merge(m, src)
}
func (m *GeneralMerchants) XXX_Size() int {
	return xxx_messageInfo_GeneralMerchants.Size(m)
}
func (m *GeneralMerchants) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralMerchants.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralMerchants proto.InternalMessageInfo

func (m *GeneralMerchants) GetGeneralMerchants() []*GeneralMerchant {
	if m != nil {
		return m.GeneralMerchants
	}
	return nil
}

func init() {
	proto.RegisterType((*GeneralMerchant)(nil), "generalmerchant.GeneralMerchant")
	proto.RegisterType((*GeneralMerchants)(nil), "generalmerchant.GeneralMerchants")
}

func init() {
	proto.RegisterFile("proto/general-merchant.proto", fileDescriptor_da8993875e4e54cb)
}

var fileDescriptor_da8993875e4e54cb = []byte{
	// 239 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xd0, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x06, 0x60, 0xba, 0x5d, 0xbb, 0x76, 0x2a, 0xee, 0x32, 0x07, 0x89, 0xb0, 0x60, 0xd8, 0x53,
	0x2f, 0x56, 0xd0, 0x37, 0xf0, 0xe2, 0x45, 0x2f, 0xc5, 0xbb, 0x8e, 0xed, 0x50, 0x03, 0xbb, 0x49,
	0x48, 0x72, 0x10, 0xdf, 0xd5, 0x77, 0x91, 0x9d, 0x56, 0x94, 0x7a, 0x9b, 0x7c, 0x7f, 0x86, 0x4c,
	0x06, 0xb6, 0x3e, 0xb8, 0xe4, 0x6e, 0x06, 0xb6, 0x1c, 0x68, 0x7f, 0x7d, 0xe0, 0xd0, 0xbd, 0x93,
	0x4d, 0x8d, 0x30, 0xae, 0x27, 0xff, 0xe1, 0xdd, 0x57, 0x06, 0xeb, 0x87, 0xd1, 0x9e, 0x26, 0xc3,
	0x73, 0x58, 0x98, 0x5e, 0x65, 0x3a, 0xab, 0xcb, 0x76, 0x61, 0x7a, 0x44, 0x58, 0x5a, 0x3a, 0xb0,
	0x5a, 0x88, 0x48, 0x8d, 0x5b, 0x28, 0xf7, 0xae, 0xa3, 0x64, 0x9c, 0x8d, 0x2a, 0xd7, 0x79, 0x5d,
	0xb6, 0xbf, 0x80, 0x97, 0x70, 0x4a, 0xde, 0xbc, 0x24, 0x1a, 0xa2, 0x5a, 0x4a, 0xb8, 0x22, 0x6f,
	0x9e, 0x69, 0x88, 0x78, 0x05, 0x55, 0xec, 0x02, 0x79, 0x1e, 0xd3, 0x13, 0x49, 0x61, 0x24, 0xb9,
	0x70, 0x01, 0x45, 0xe4, 0x2e, 0xb9, 0xa0, 0x0a, 0x79, 0x6f, 0x3a, 0x1d, 0xa7, 0x88, 0xe6, 0x93,
	0xd5, 0x6a, 0x9c, 0xe2, 0x58, 0xa3, 0x86, 0x8a, 0x3f, 0x3c, 0xdb, 0xc8, 0xf7, 0x64, 0x7b, 0x75,
	0x26, 0xd1, 0x5f, 0xda, 0xbd, 0xc2, 0x66, 0xf6, 0xbd, 0x88, 0x8f, 0xb0, 0x19, 0x66, 0xa6, 0x32,
	0x9d, 0xd7, 0xd5, 0xad, 0x6e, 0x66, 0xfb, 0x69, 0x66, 0xcd, 0xed, 0xbf, 0xce, 0xb7, 0x42, 0x36,
	0x7b, 0xf7, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x69, 0x4b, 0xf3, 0x3e, 0x79, 0x01, 0x00, 0x00,
}
