apiVersion: v1
kind: Service
metadata:
  name: micro-api
  namespace: default
  labels:
    name: micro-api
    micro: service
spec:
  ports:
    - name: https
      port: 80
      targetPort: 80
  selector:
    name: micro-api
    micro: service
  type: LoadBalancer