
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: pod-viewer-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "patch", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: "pod-viewer-role-binding"
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: "pod-viewer-role"
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: "default"
    namespace: default