// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/merchant/merchant.proto

package merchant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Merchant struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Locations            []*Location `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	Tags                 []*Tag      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	ContactPhone         string      `protobuf:"bytes,5,opt,name=contactPhone,proto3" json:"contactPhone,omitempty"`
	ContactEmail         string      `protobuf:"bytes,6,opt,name=contactEmail,proto3" json:"contactEmail,omitempty"`
	Rate                 float32     `protobuf:"fixed32,7,opt,name=rate,proto3" json:"rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9db34436ab21601, []int{0}
}

func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Merchant.Unmarshal(m, b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
}
func (m *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(m, src)
}
func (m *Merchant) XXX_Size() int {
	return xxx_messageInfo_Merchant.Size(m)
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Merchant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Merchant) GetLocations() []*Location {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *Merchant) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Merchant) GetContactPhone() string {
	if m != nil {
		return m.ContactPhone
	}
	return ""
}

func (m *Merchant) GetContactEmail() string {
	if m != nil {
		return m.ContactEmail
	}
	return ""
}

func (m *Merchant) GetRate() float32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

type Location struct {
	Location             string   `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Location) Reset()         { *m = Location{} }
func (m *Location) String() string { return proto.CompactTextString(m) }
func (*Location) ProtoMessage()    {}
func (*Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9db34436ab21601, []int{1}
}

func (m *Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Location.Unmarshal(m, b)
}
func (m *Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Location.Marshal(b, m, deterministic)
}
func (m *Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Location.Merge(m, src)
}
func (m *Location) XXX_Size() int {
	return xxx_messageInfo_Location.Size(m)
}
func (m *Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Location proto.InternalMessageInfo

func (m *Location) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

type Tag struct {
	Tag                  string   `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9db34436ab21601, []int{2}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetTag() string {
	if m != nil {
		return m.Tag
	}
	return ""
}

type CreateResponse struct {
	Created              bool      `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Merchant             *Merchant `protobuf:"bytes,2,opt,name=merchant,proto3" json:"merchant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9db34436ab21601, []int{3}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateResponse) GetMerchant() *Merchant {
	if m != nil {
		return m.Merchant
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9db34436ab21601, []int{4}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Merchants            []*Merchant `protobuf:"bytes,1,rep,name=merchants,proto3" json:"merchants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9db34436ab21601, []int{5}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetMerchants() []*Merchant {
	if m != nil {
		return m.Merchants
	}
	return nil
}

func init() {
	proto.RegisterType((*Merchant)(nil), "merchant.Merchant")
	proto.RegisterType((*Location)(nil), "merchant.Location")
	proto.RegisterType((*Tag)(nil), "merchant.Tag")
	proto.RegisterType((*CreateResponse)(nil), "merchant.CreateResponse")
	proto.RegisterType((*GetRequest)(nil), "merchant.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "merchant.GetResponse")
}

func init() { proto.RegisterFile("proto/merchant/merchant.proto", fileDescriptor_e9db34436ab21601) }

var fileDescriptor_e9db34436ab21601 = []byte{
	// 338 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4a, 0xf3, 0x40,
	0x10, 0xc7, 0xbf, 0x24, 0xfd, 0xda, 0x74, 0xaa, 0x55, 0x06, 0xc5, 0xa5, 0x28, 0xd4, 0x1c, 0xa4,
	0xa7, 0x5a, 0xea, 0x55, 0x50, 0x10, 0xf1, 0xa2, 0x20, 0x6b, 0x4f, 0xde, 0xd6, 0x74, 0x48, 0x03,
	0x6d, 0xb6, 0x26, 0xab, 0xef, 0xe1, 0x13, 0xfa, 0x2a, 0xd2, 0x31, 0xbb, 0x6b, 0xaa, 0xb7, 0x99,
	0xff, 0xfc, 0x67, 0x76, 0xe6, 0x97, 0xc0, 0xc9, 0xba, 0xd4, 0x46, 0x9f, 0xaf, 0xa8, 0x4c, 0x17,
	0xaa, 0x30, 0x2e, 0x18, 0xb3, 0x8e, 0xb1, 0xcd, 0x93, 0xcf, 0x00, 0xe2, 0x87, 0x3a, 0xc1, 0x3e,
	0x84, 0xf9, 0x5c, 0x04, 0xc3, 0x60, 0xd4, 0x95, 0x61, 0x3e, 0x47, 0x84, 0x56, 0xa1, 0x56, 0x24,
	0x42, 0x56, 0x38, 0xc6, 0x09, 0x74, 0x97, 0x3a, 0x55, 0x26, 0xd7, 0x45, 0x25, 0xa2, 0x61, 0x34,
	0xea, 0x4d, 0x71, 0xec, 0xc6, 0xdf, 0xd7, 0x25, 0xe9, 0x4d, 0x78, 0x0a, 0x2d, 0xa3, 0xb2, 0x4a,
	0xb4, 0xd8, 0xbc, 0xeb, 0xcd, 0x33, 0x95, 0x49, 0x2e, 0x61, 0x02, 0x3b, 0xa9, 0x2e, 0x8c, 0x4a,
	0xcd, 0xe3, 0x42, 0x17, 0x24, 0xfe, 0xf3, 0x83, 0x0d, 0xed, 0x87, 0xe7, 0x76, 0xa5, 0xf2, 0xa5,
	0x68, 0x37, 0x3c, 0xac, 0x6d, 0x16, 0x2e, 0x95, 0x21, 0xd1, 0x19, 0x06, 0xa3, 0x50, 0x72, 0x9c,
	0x9c, 0x41, 0x6c, 0xb7, 0xc2, 0x01, 0xc4, 0x76, 0xaf, 0xfa, 0x4c, 0x97, 0x27, 0x47, 0x10, 0xcd,
	0x54, 0x86, 0xfb, 0x10, 0x19, 0x95, 0xd5, 0xd5, 0x4d, 0x98, 0x3c, 0x43, 0xff, 0xa6, 0x24, 0x65,
	0x48, 0x52, 0xb5, 0xd6, 0x45, 0x45, 0x28, 0xa0, 0x93, 0xb2, 0xf2, 0x0d, 0x2b, 0x96, 0x36, 0xc5,
	0x31, 0x38, 0xb4, 0x4c, 0xad, 0x01, 0xc7, 0x72, 0x96, 0x1e, 0xff, 0x31, 0xc0, 0x1d, 0x19, 0x49,
	0xaf, 0x6f, 0x54, 0xfd, 0xe2, 0x9f, 0x5c, 0x41, 0x8f, 0xab, 0xf5, 0xb3, 0x13, 0xe8, 0xda, 0xc6,
	0x4a, 0x04, 0xdb, 0xe8, 0xdd, 0x74, 0x6f, 0x9a, 0x7e, 0x04, 0xb0, 0x67, 0xf5, 0x27, 0x2a, 0xdf,
	0xf3, 0x94, 0xf0, 0xda, 0x9e, 0xe3, 0x3e, 0xfb, 0x1f, 0x43, 0x06, 0xc2, 0x6b, 0xcd, 0xe3, 0x93,
	0x7f, 0x78, 0xc9, 0x6b, 0xb9, 0xf6, 0x03, 0x6f, 0xf5, 0xb7, 0x0c, 0x0e, 0xb7, 0x54, 0xdb, 0xfd,
	0xd2, 0xe6, 0x5f, 0xf0, 0xe2, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xc0, 0x31, 0x04, 0xa3, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for MerchantService service

type MerchantServiceClient interface {
	CreateMerchant(ctx context.Context, in *Merchant, opts ...client.CallOption) (*CreateResponse, error)
	GetMerchant(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
}

type merchantServiceClient struct {
	c           client.Client
	serviceName string
}

func NewMerchantServiceClient(serviceName string, c client.Client) MerchantServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "merchant"
	}
	return &merchantServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *merchantServiceClient) CreateMerchant(ctx context.Context, in *Merchant, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "MerchantService.CreateMerchant", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *merchantServiceClient) GetMerchant(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.serviceName, "MerchantService.GetMerchant", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MerchantService service

type MerchantServiceHandler interface {
	CreateMerchant(context.Context, *Merchant, *CreateResponse) error
	GetMerchant(context.Context, *GetRequest, *GetResponse) error
}

func RegisterMerchantServiceHandler(s server.Server, hdlr MerchantServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&MerchantService{hdlr}, opts...))
}

type MerchantService struct {
	MerchantServiceHandler
}

func (h *MerchantService) CreateMerchant(ctx context.Context, in *Merchant, out *CreateResponse) error {
	return h.MerchantServiceHandler.CreateMerchant(ctx, in, out)
}

func (h *MerchantService) GetMerchant(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.MerchantServiceHandler.GetMerchant(ctx, in, out)
}
