// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package transaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction_Type int32

const (
	Transaction_CREDIT      Transaction_Type = 0
	Transaction_DEBIT       Transaction_Type = 1
	Transaction_CONTACTLESS Transaction_Type = 2
)

var Transaction_Type_name = map[int32]string{
	0: "CREDIT",
	1: "DEBIT",
	2: "CONTACTLESS",
}

var Transaction_Type_value = map[string]int32{
	"CREDIT":      0,
	"DEBIT":       1,
	"CONTACTLESS": 2,
}

func (x Transaction_Type) String() string {
	return proto.EnumName(Transaction_Type_name, int32(x))
}

func (Transaction_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0, 0}
}

type Transaction struct {
	Id                   string           `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            string           `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ProcessedTimestamp   string           `protobuf:"bytes,3,opt,name=processed_timestamp,json=processedTimestamp,proto3" json:"processed_timestamp,omitempty"`
	UserId               string           `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AccountId            string           `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	MerchantId           string           `protobuf:"bytes,6,opt,name=merchant_id,json=merchantId,proto3" json:"merchant_id,omitempty"`
	Amount               float64          `protobuf:"fixed64,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency             string           `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	Location             string           `protobuf:"bytes,9,opt,name=location,proto3" json:"location,omitempty"`
	Rating               int32            `protobuf:"varint,10,opt,name=rating,proto3" json:"rating,omitempty"`
	ApiTags              []string         `protobuf:"bytes,11,rep,name=api_tags,json=apiTags,proto3" json:"api_tags,omitempty"`
	OtisTags             []string         `protobuf:"bytes,12,rep,name=otis_tags,json=otisTags,proto3" json:"otis_tags,omitempty"`
	Holidays             []string         `protobuf:"bytes,14,rep,name=holidays,proto3" json:"holidays,omitempty"`
	Type                 Transaction_Type `protobuf:"varint,15,opt,name=type,proto3,enum=transaction.Transaction_Type" json:"type,omitempty"`
	Online               bool             `protobuf:"varint,16,opt,name=online,proto3" json:"online,omitempty"`
	CashbackValid        bool             `protobuf:"varint,17,opt,name=cashback_valid,json=cashbackValid,proto3" json:"cashback_valid,omitempty"`
	MerchantName         string           `protobuf:"bytes,18,opt,name=merchant_name,json=merchantName,proto3" json:"merchant_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *Transaction) GetProcessedTimestamp() string {
	if m != nil {
		return m.ProcessedTimestamp
	}
	return ""
}

func (m *Transaction) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Transaction) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Transaction) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *Transaction) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Transaction) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Transaction) GetRating() int32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Transaction) GetApiTags() []string {
	if m != nil {
		return m.ApiTags
	}
	return nil
}

func (m *Transaction) GetOtisTags() []string {
	if m != nil {
		return m.OtisTags
	}
	return nil
}

func (m *Transaction) GetHolidays() []string {
	if m != nil {
		return m.Holidays
	}
	return nil
}

func (m *Transaction) GetType() Transaction_Type {
	if m != nil {
		return m.Type
	}
	return Transaction_CREDIT
}

func (m *Transaction) GetOnline() bool {
	if m != nil {
		return m.Online
	}
	return false
}

func (m *Transaction) GetCashbackValid() bool {
	if m != nil {
		return m.CashbackValid
	}
	return false
}

func (m *Transaction) GetMerchantName() string {
	if m != nil {
		return m.MerchantName
	}
	return ""
}

func init() {
	proto.RegisterEnum("transaction.Transaction_Type", Transaction_Type_name, Transaction_Type_value)
	proto.RegisterType((*Transaction)(nil), "transaction.Transaction")
}

func init() {
	proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490)
}

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0xd1, 0x6e, 0x9b, 0x30,
	0x14, 0x86, 0x47, 0x9a, 0x10, 0x38, 0xb4, 0x69, 0x7a, 0x26, 0x6d, 0x5e, 0xb7, 0x6a, 0xa8, 0xd3,
	0x24, 0xae, 0x32, 0x6d, 0x7b, 0x82, 0x2d, 0xcd, 0x05, 0xd2, 0xd4, 0x49, 0x14, 0xed, 0x36, 0x3a,
	0xb5, 0xad, 0xc4, 0x5a, 0xc0, 0x08, 0x3b, 0x93, 0xf2, 0x86, 0x7b, 0xac, 0xca, 0x26, 0x90, 0xdc,
	0xf1, 0x7f, 0xdf, 0x6f, 0x0e, 0x07, 0x80, 0x1b, 0xdb, 0x52, 0x6d, 0x88, 0x5b, 0xa5, 0xeb, 0x45,
	0xd3, 0x6a, 0xab, 0x31, 0x39, 0x43, 0xf7, 0xff, 0xc7, 0x90, 0x94, 0xa7, 0x8c, 0x33, 0x18, 0x29,
	0xc1, 0x82, 0x34, 0xc8, 0xe2, 0x62, 0xa4, 0x04, 0x7e, 0x80, 0xd8, 0xaa, 0x4a, 0x1a, 0x4b, 0x55,
	0xc3, 0x46, 0x1e, 0x9f, 0x00, 0x7e, 0x81, 0xd7, 0x4d, 0xab, 0xb9, 0x34, 0x46, 0x8a, 0xf5, 0xa9,
	0x77, 0xe1, 0x7b, 0x38, 0xa8, 0x72, 0x38, 0xf0, 0x16, 0xa6, 0x7b, 0x23, 0xdb, 0xb5, 0x12, 0x6c,
	0xec, 0x4b, 0xa1, 0x8b, 0xb9, 0xc0, 0x3b, 0x00, 0xe2, 0x5c, 0xef, 0x6b, 0xeb, 0xdc, 0xa4, 0x1b,
	0x74, 0x24, 0xb9, 0xc0, 0x8f, 0x90, 0x54, 0xb2, 0xe5, 0x5b, 0xea, 0x7c, 0xe8, 0x3d, 0xf4, 0x28,
	0x17, 0xf8, 0x06, 0x42, 0xaa, 0x5c, 0x99, 0x4d, 0xd3, 0x20, 0x0b, 0x8a, 0x63, 0xc2, 0x5b, 0x88,
	0xf8, 0xbe, 0x6d, 0x65, 0xcd, 0x0f, 0x2c, 0xf2, 0xa7, 0x86, 0xec, 0xdc, 0x4e, 0x73, 0x72, 0x7b,
	0xb3, 0xb8, 0x73, 0x7d, 0x76, 0xf7, 0x6b, 0xc9, 0xaa, 0x7a, 0xc3, 0x20, 0x0d, 0xb2, 0x49, 0x71,
	0x4c, 0xf8, 0x0e, 0x22, 0x6a, 0xd4, 0xda, 0xd2, 0xc6, 0xb0, 0x24, 0xbd, 0xc8, 0xe2, 0x62, 0x4a,
	0x8d, 0x2a, 0x69, 0x63, 0xf0, 0x3d, 0xc4, 0xda, 0x2a, 0xd3, 0xb9, 0x4b, 0xef, 0x22, 0x07, 0xbc,
	0xbc, 0x85, 0x68, 0xab, 0x77, 0x4a, 0xd0, 0xc1, 0xb0, 0x59, 0xe7, 0xfa, 0x8c, 0x5f, 0x61, 0x6c,
	0x0f, 0x8d, 0x64, 0xd7, 0x69, 0x90, 0xcd, 0xbe, 0xdd, 0x2d, 0xce, 0x3f, 0x59, 0x79, 0x7e, 0x7d,
	0x68, 0x64, 0xe1, 0xab, 0xee, 0xf1, 0x74, 0xbd, 0x53, 0xb5, 0x64, 0xf3, 0x34, 0xc8, 0xa2, 0xe2,
	0x98, 0xf0, 0x33, 0xcc, 0x38, 0x99, 0xed, 0x33, 0xf1, 0xbf, 0xeb, 0x7f, 0xb4, 0x53, 0x82, 0xdd,
	0x78, 0x7f, 0xd5, 0xd3, 0x3f, 0x0e, 0xe2, 0x27, 0xb8, 0x1a, 0x5e, 0x67, 0x4d, 0x95, 0x64, 0xe8,
	0xd7, 0xbf, 0xec, 0xe1, 0x23, 0x55, 0xf2, 0x7e, 0x01, 0x63, 0x37, 0x11, 0x01, 0xc2, 0x65, 0xb1,
	0x7a, 0xc8, 0xcb, 0xf9, 0x2b, 0x8c, 0x61, 0xf2, 0xb0, 0xfa, 0x99, 0x97, 0xf3, 0x00, 0xaf, 0x21,
	0x59, 0xfe, 0x7e, 0x2c, 0x7f, 0x2c, 0xcb, 0x5f, 0xab, 0xa7, 0xa7, 0xf9, 0xe8, 0x39, 0xf4, 0xbf,
	0xd7, 0xf7, 0x97, 0x00, 0x00, 0x00, 0xff, 0xff, 0x22, 0x2b, 0x98, 0x7c, 0x73, 0x02, 0x00, 0x00,
}
