image: golang:latest

variables:
    REPO_NAME: gitlab.com/otis-team/backend

before_script:
    - mkdir  -p /$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR /$REPO_NAME
    - cd /$REPO_NAME

stages:
  - test

lint:
  stage: test
  script:
    - make lint