image: golang:latest

variables:
    REPO_NAME: gitlab.com/otis-team/backend

stages:
  - test
  - build

lint:
  stage: test
  before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go get -u golang.org/x/lint/golint
  script:
    - golint -set_exit_status ./...
    
container_registry:
    stage: build
    only:
     - master
    image: docker:stable
    services:
     - docker:dind
    script: 
     - docker login -u 1fruBCF2_5aLxaF3NBcf -p $CI_JOB_TOKEN $CI_REGISTRY
     - docker build -t registry.gitlab.com/otis-team/backend ./service/merchant/
     - docker build -t registry.gitlab.com/otis-team/backend ./service/user/
#     - docker build -t registry.gitlab.com/otis-team/backend ./service/transaction/
#     - docker build -t registry.gitlab.com/otis-team/backend ./api/merchant/
#     - docker build -t registry.gitlab.com/otis-team/backend ./api/user/
     - docker push registry.gitlab.com/otis-team/backend


     