image: golang:latest

variables:
    REPO_NAME: gitlab.com/otis-team/backend

before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go get -u golang.org/x/lint/golint

stages:
  - test
  - build

lint:
  stage: test
  script:
    - golint -set_exit_status ./...
    
container_registry:
    stage: build
    script: 
     - docker build -t registry.gitlab.com/otis-team/backend ./service/merchant/
     - docker build -t registry.gitlab.com/otis-team/backend ./service/user/
     - docker build -t registry.gitlab.com/otis-team/backend ./service/transaction/
     - docker build -t registry.gitlab.com/otis-team/backend ./api/merchant/
     - docker build -t registry.gitlab.com/otis-team/backend ./api/user/ 
     - docker push registry.gitlab.com/otis-team/backend


     