image: golang:latest

variables:
    REPO_NAME: gitlab.com/otis-team/backend

before_script:
    - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
    - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
    - cd $GOPATH/src/$REPO_NAME
    - go env GOPATH GOBIN
    - export GOPATH=$HOME/go
    - export GOBIN=$HOME/go/bin
    - mkdir -p $GOPATH/src/golang.org/x 
    - git clone https://go.googlesource.com/lint $GOPATH/src/golang.org/x/lint 
    - go get -u golang.org/x/lint/golint

stages:
  - test

lint:
  stage: test
  script:
    - golint ./...