# docker-compose.yml
version: '3.5'

services:

  api_gateway:
    image: microhq/micro:latest
    restart: always
    command: api --handler=api
    ports:
      - 8080:8080
    networks:
      - api-gateway-tier

  api_merchant:
    restart: always
    container_name: "go.micro.api.merchant"
    build:
      context: ./api/merchant/
      dockerfile: Dockerfile
      args:
        - gitlab_user=otis_cj
        - gitlab_token=1fruBCF2_5aLxaF3NBcf
    depends_on:
      - api_gateway
    ports:
      - 50051:50051
    networks:
      - api-gateway-tier
      - api-merchant-tier

  service_merchant:
    restart: always
    container_name: "go.micro.service.merchant"
    build: ./service/merchant/
    ports:
      - 50052:50052
    links:
      - datastore
    networks:
      - api-gateway-tier
      - api-merchant-tier
      - service-tier
    depends_on:
      - datastore
    environment:
      DB_HOST: "mongodb://datastore:27017"

  service_user:
    restart: always
    container_name: "go.micro.service.user"
    build: ./service/user/
    ports:
      - 50053:50053
    links:
      - datastore
    networks:
      - api-gateway-tier
      - api-merchant-tier
      - service-tier
    depends_on:
      - datastore
    environment:
      DB_HOST: "mongodb://datastore:27017"

  datastore:
    image: mongo:latest
    container_name: "datastore"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONG_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    networks:
      - service-tier
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null

networks:
  api-gateway-tier:
    name: api-gateway-tier
  api-merchant-tier:
    name: api-merchant-tier
  service-tier:
    name: service-tier