# docker-compose.yml
version: '3.5'

services:

  api_gateway:
    image: ${OTIS_CI_REGISTRY}/otis_team/backend/api-gateway:${OTIS_DOCKER_IMAGETAG}
    restart: always
    build:
      context: ${OTIS_HOME}
      dockerfile: ${OTIS_HOME}/api-gateway/Dockerfile
    expose:
      - "3005"
    volumes:
      - ${OTIS_HOME}/certs:/app/certs
      - ${OTIS_HOME}/api-gateway/gateway-config.js:/app/api-gateway/gateway-config.js
    env_file:
      - .env.local
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "3000:3000"
    networks:
      - api-gateway-tier

  merchant_service:
    image: ${OTIS_CI_REGISTRY}/otis_team/backend/service/merchant:${OTIS_DOCKER_IMAGETAG}
    restart: always
    build:
      context: ${OTIS_HOME}
      dockerfile: ${OTIS_HOME}/service/merchant/Dockerfile
    expose:
      - "3000"
    volumes:
      - ${OTIS_HOME}/certs:/app/certs
      - ${OTIS_HOME}/service/merchant/service-config.py:/app/merchant-service/service-config.py
    env_file:
      - .env.local
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "3005:3005"
    networks:
      - api-gateway-tier

#  service_merchant:
#    restart: always
#    container_name: "go.micro.service.merchant"
#    build:
#      context: ./service/merchant/
#      dockerfile: Dockerfile
#      args:
#        - gitlab_user=gitlab+deploy-token-154792
#        - gitlab_token=ZbKzbXzeapzLsNkxomxx
#    ports:
#      - 50053:50053
#    networks:
#      - api-gateway-tier
#      - api-merchant-tier
#
#  service_user:
#    restart: always
#    container_name: "go.micro.service.user"
#    build:
#      context: ./service/user/
#      dockerfile: Dockerfile
#      args:
#        - gitlab_user=gitlab+deploy-token-154792
#        - gitlab_token=ZbKzbXzeapzLsNkxomxx
#    ports:
#      - 50054:50054
#    networks:
#      - api-gateway-tier
#      - api-user-tier
#
#  service_transaction:
#    restart: always
#    container_name: "go.micro.service.transaction"
#    build:
#      context: ./service/transaction/
#      dockerfile: Dockerfile
#      args:
#        - gitlab_user=gitlab+deploy-token-154792
#        - gitlab_token=ZbKzbXzeapzLsNkxomxx
#    ports:
#      - 50055:50055
#    networks:
#      - api-gateway-tier
#      - api-transaction-tier

networks:
  api-gateway-tier:
    name: api-gateway-tier
  api-merchant-tier:
    name: api-merchant-tier
  api-user-tier:
    name: api-user-tier
  api-transaction-tier:
    name: api-transaction-tier
