// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction/transaction.proto

package transaction

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	TransactionId        string   `protobuf:"bytes,1,opt,name=transactionId,proto3" json:"transactionId,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"`
	MerchantId           string   `protobuf:"bytes,3,opt,name=merchantId,proto3" json:"merchantId,omitempty"`
	StoreId              string   `protobuf:"bytes,4,opt,name=storeId,proto3" json:"storeId,omitempty"`
	Gender               string   `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	University           string   `protobuf:"bytes,6,opt,name=university,proto3" json:"university,omitempty"`
	Date                 string   `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Time                 string   `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	Accounts             *Account `protobuf:"bytes,9,opt,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_284c03442be38d9f, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

func (m *Transaction) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Transaction) GetMerchantId() string {
	if m != nil {
		return m.MerchantId
	}
	return ""
}

func (m *Transaction) GetStoreId() string {
	if m != nil {
		return m.StoreId
	}
	return ""
}

func (m *Transaction) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *Transaction) GetUniversity() string {
	if m != nil {
		return m.University
	}
	return ""
}

func (m *Transaction) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Transaction) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Transaction) GetAccounts() *Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Account struct {
	AccountID            []string `protobuf:"bytes,1,rep,name=accountID,proto3" json:"accountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_284c03442be38d9f, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountID() []string {
	if m != nil {
		return m.AccountID
	}
	return nil
}

type CreateResponse struct {
	Created              bool         `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Transaction          *Transaction `protobuf:"bytes,2,opt,name=Transaction,proto3" json:"Transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_284c03442be38d9f, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type IdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_284c03442be38d9f, []int{3}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Transactions struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_284c03442be38d9f, []int{4}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "transaction.Transaction")
	proto.RegisterType((*Account)(nil), "transaction.Account")
	proto.RegisterType((*CreateResponse)(nil), "transaction.CreateResponse")
	proto.RegisterType((*IdRequest)(nil), "transaction.IdRequest")
	proto.RegisterType((*Transactions)(nil), "transaction.Transactions")
}

func init() { proto.RegisterFile("transaction/transaction.proto", fileDescriptor_284c03442be38d9f) }

var fileDescriptor_284c03442be38d9f = []byte{
	// 362 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x4e, 0xf3, 0x30,
	0x10, 0xc5, 0x9b, 0xb4, 0x5f, 0xdb, 0x4c, 0xfa, 0x15, 0x31, 0x42, 0x95, 0x69, 0x01, 0x55, 0x11,
	0x12, 0x5d, 0x15, 0x54, 0x76, 0x88, 0x0d, 0x02, 0x81, 0x22, 0x75, 0x15, 0xb8, 0x40, 0x88, 0x07,
	0xc8, 0xa2, 0x49, 0xb1, 0x9d, 0x4a, 0x9c, 0x84, 0x3b, 0x70, 0x4a, 0x14, 0xbb, 0x7f, 0xec, 0x45,
	0xd9, 0x79, 0x7e, 0x6f, 0xf2, 0x3c, 0xf3, 0x62, 0x38, 0x55, 0x22, 0x2d, 0x64, 0x9a, 0xa9, 0xbc,
	0x2c, 0x2e, 0xad, 0xf3, 0x74, 0x29, 0x4a, 0x55, 0x62, 0x68, 0xa1, 0xe8, 0xdb, 0x87, 0xf0, 0x65,
	0x57, 0xe3, 0x39, 0xfc, 0xb7, 0xe4, 0x98, 0x33, 0x6f, 0xec, 0x4d, 0x82, 0xc4, 0x85, 0x38, 0x80,
	0x76, 0x25, 0x49, 0xc4, 0x9c, 0xf9, 0x5a, 0x5e, 0x57, 0x78, 0x06, 0xb0, 0x20, 0x91, 0x7d, 0xa4,
	0x85, 0x8a, 0x39, 0x6b, 0x6a, 0xcd, 0x22, 0xc8, 0xa0, 0x23, 0x55, 0x29, 0x28, 0xe6, 0xac, 0xa5,
	0xc5, 0x4d, 0x59, 0x3b, 0xbe, 0x53, 0xc1, 0x49, 0xb0, 0x7f, 0xc6, 0xd1, 0x54, 0xb5, 0x63, 0x55,
	0xe4, 0x2b, 0x12, 0x32, 0x57, 0x5f, 0xac, 0x6d, 0x1c, 0x77, 0x04, 0x11, 0x5a, 0x3c, 0x55, 0xc4,
	0x3a, 0x5a, 0xd1, 0xe7, 0x9a, 0xa9, 0x7c, 0x41, 0xac, 0x6b, 0x58, 0x7d, 0xc6, 0x2b, 0xe8, 0xa6,
	0x59, 0x56, 0x56, 0x85, 0x92, 0x2c, 0x18, 0x7b, 0x93, 0x70, 0x76, 0x34, 0xb5, 0xa3, 0xb9, 0x33,
	0x62, 0xb2, 0xed, 0x8a, 0x2e, 0xa0, 0xb3, 0x86, 0x78, 0x02, 0xc1, 0x1a, 0xc7, 0x0f, 0xcc, 0x1b,
	0x37, 0x27, 0x41, 0xb2, 0x03, 0xd1, 0x1b, 0xf4, 0xef, 0x05, 0xa5, 0x8a, 0x12, 0x92, 0xcb, 0xb2,
	0x90, 0x54, 0xaf, 0x99, 0x69, 0x62, 0xe2, 0xeb, 0x26, 0x9b, 0x12, 0x6f, 0x9c, 0xb4, 0x75, 0x7a,
	0xe1, 0x8c, 0x39, 0x93, 0x58, 0x7a, 0x62, 0x37, 0x47, 0x23, 0x08, 0x62, 0x9e, 0xd0, 0x67, 0x45,
	0x52, 0x61, 0x1f, 0xfc, 0x7c, 0xf3, 0x73, 0xfc, 0x9c, 0x47, 0x73, 0xe8, 0x59, 0xbd, 0x12, 0x6f,
	0xa1, 0x67, 0x99, 0x4a, 0x3d, 0xf5, 0x5f, 0x37, 0x39, 0xdd, 0xb3, 0x1f, 0x0f, 0xd0, 0x52, 0x9f,
	0x49, 0xac, 0xf2, 0x8c, 0x70, 0x0e, 0x87, 0x66, 0x53, 0xfb, 0xc5, 0xec, 0xf5, 0x1c, 0x8e, 0x1c,
	0xc5, 0xcd, 0x28, 0x6a, 0xe0, 0x23, 0x1c, 0x3c, 0x91, 0x72, 0xa6, 0x1e, 0x38, 0x5f, 0x6c, 0xb7,
	0x1d, 0x1e, 0xef, 0xbb, 0x43, 0x46, 0x8d, 0xd7, 0xb6, 0x7e, 0xd6, 0xd7, 0xbf, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xea, 0xc7, 0xb1, 0x1c, 0xf7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TransactionServiceClient is the client API for TransactionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactionServiceClient interface {
	CreateTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*CreateResponse, error)
	GetTransactions(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Transactions, error)
}

type transactionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionServiceClient(cc grpc.ClientConnInterface) TransactionServiceClient {
	return &transactionServiceClient{cc}
}

func (c *transactionServiceClient) CreateTransaction(ctx context.Context, in *Transaction, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/transaction.TransactionService/CreateTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactionServiceClient) GetTransactions(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Transactions, error) {
	out := new(Transactions)
	err := c.cc.Invoke(ctx, "/transaction.TransactionService/GetTransactions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionServiceServer is the server API for TransactionService service.
type TransactionServiceServer interface {
	CreateTransaction(context.Context, *Transaction) (*CreateResponse, error)
	GetTransactions(context.Context, *IdRequest) (*Transactions, error)
}

// UnimplementedTransactionServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTransactionServiceServer struct {
}

func (*UnimplementedTransactionServiceServer) CreateTransaction(ctx context.Context, req *Transaction) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransaction not implemented")
}
func (*UnimplementedTransactionServiceServer) GetTransactions(ctx context.Context, req *IdRequest) (*Transactions, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransactions not implemented")
}

func RegisterTransactionServiceServer(s *grpc.Server, srv TransactionServiceServer) {
	s.RegisterService(&_TransactionService_serviceDesc, srv)
}

func _TransactionService_CreateTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transaction)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).CreateTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionService/CreateTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).CreateTransaction(ctx, req.(*Transaction))
	}
	return interceptor(ctx, in, info, handler)
}

func _TransactionService_GetTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionServiceServer).GetTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transaction.TransactionService/GetTransactions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionServiceServer).GetTransactions(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TransactionService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transaction.TransactionService",
	HandlerType: (*TransactionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTransaction",
			Handler:    _TransactionService_CreateTransaction_Handler,
		},
		{
			MethodName: "GetTransactions",
			Handler:    _TransactionService_GetTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "transaction/transaction.proto",
}
