// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/transaction/transaction.proto

package transaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	MerchantID           string   `protobuf:"bytes,3,opt,name=merchantID,proto3" json:"merchantID,omitempty"`
	StoreID              string   `protobuf:"bytes,4,opt,name=storeID,proto3" json:"storeID,omitempty"`
	Date                 string   `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Time                 string   `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2129939cf85d765e, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *Transaction) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Transaction) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *Transaction) GetStoreID() string {
	if m != nil {
		return m.StoreID
	}
	return ""
}

func (m *Transaction) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Transaction) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

type CreateResponse struct {
	Created              bool         `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Transaction          *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2129939cf85d765e, []int{1}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateResponse) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

type IdRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IdRequest) Reset()         { *m = IdRequest{} }
func (m *IdRequest) String() string { return proto.CompactTextString(m) }
func (*IdRequest) ProtoMessage()    {}
func (*IdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2129939cf85d765e, []int{2}
}

func (m *IdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IdRequest.Unmarshal(m, b)
}
func (m *IdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IdRequest.Marshal(b, m, deterministic)
}
func (m *IdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IdRequest.Merge(m, src)
}
func (m *IdRequest) XXX_Size() int {
	return xxx_messageInfo_IdRequest.Size(m)
}
func (m *IdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IdRequest proto.InternalMessageInfo

func (m *IdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Transactions struct {
	Transactions         []*Transaction `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Transactions) Reset()         { *m = Transactions{} }
func (m *Transactions) String() string { return proto.CompactTextString(m) }
func (*Transactions) ProtoMessage()    {}
func (*Transactions) Descriptor() ([]byte, []int) {
	return fileDescriptor_2129939cf85d765e, []int{3}
}

func (m *Transactions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transactions.Unmarshal(m, b)
}
func (m *Transactions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transactions.Marshal(b, m, deterministic)
}
func (m *Transactions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transactions.Merge(m, src)
}
func (m *Transactions) XXX_Size() int {
	return xxx_messageInfo_Transactions.Size(m)
}
func (m *Transactions) XXX_DiscardUnknown() {
	xxx_messageInfo_Transactions.DiscardUnknown(m)
}

var xxx_messageInfo_Transactions proto.InternalMessageInfo

func (m *Transactions) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "transaction.Transaction")
	proto.RegisterType((*CreateResponse)(nil), "transaction.CreateResponse")
	proto.RegisterType((*IdRequest)(nil), "transaction.IdRequest")
	proto.RegisterType((*Transactions)(nil), "transaction.Transactions")
}

func init() {
	proto.RegisterFile("proto/transaction/transaction.proto", fileDescriptor_2129939cf85d765e)
}

var fileDescriptor_2129939cf85d765e = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0x40, 0xf8, 0x98, 0x22, 0xc6, 0x39, 0x90, 0x15, 0x12, 0x43, 0xaa, 0x07, 0x4f, 0x98,
	0xe0, 0xcd, 0x78, 0xb3, 0xd1, 0x34, 0xe1, 0x54, 0xfd, 0x03, 0xb5, 0x1d, 0x63, 0x0f, 0xb4, 0xb8,
	0x3b, 0xf8, 0xa3, 0x4c, 0xfc, 0x8f, 0xa6, 0x03, 0xe8, 0xec, 0x01, 0x6f, 0xf3, 0xde, 0xeb, 0x7c,
	0xbc, 0xd7, 0x85, 0xcb, 0x8d, 0xad, 0xb9, 0xbe, 0x61, 0x9b, 0x55, 0x2e, 0xcb, 0xb9, 0xac, 0x2b,
	0x5d, 0x2f, 0x44, 0xc5, 0x50, 0x51, 0xd1, 0x77, 0x00, 0xe1, 0xcb, 0x1f, 0xc6, 0x2b, 0x38, 0x51,
	0x72, 0x12, 0x9b, 0x60, 0x1e, 0x5c, 0x0f, 0x53, 0x9f, 0xc4, 0x09, 0xf4, 0xb6, 0x8e, 0x6c, 0x12,
	0x9b, 0xb6, 0xc8, 0x7b, 0x84, 0x17, 0x00, 0x6b, 0xb2, 0xf9, 0x7b, 0x56, 0x71, 0x12, 0x9b, 0x8e,
	0x68, 0x8a, 0x41, 0x03, 0x7d, 0xc7, 0xb5, 0xa5, 0x24, 0x36, 0x5d, 0x11, 0x0f, 0x10, 0x11, 0xba,
	0x45, 0xc6, 0x64, 0xfa, 0x42, 0x4b, 0xdd, 0x70, 0x5c, 0xae, 0xc9, 0x0c, 0x76, 0x5c, 0x53, 0x47,
	0x6f, 0x30, 0x7e, 0xb0, 0x94, 0x31, 0xa5, 0xe4, 0x36, 0x75, 0xe5, 0xa8, 0x99, 0x99, 0x0b, 0x53,
	0xc8, 0xad, 0x83, 0xf4, 0x00, 0xf1, 0x0e, 0xb4, 0x55, 0x39, 0x35, 0x5c, 0x9a, 0x85, 0x4e, 0x44,
	0x59, 0x4f, 0xbd, 0x5c, 0x66, 0x30, 0x4c, 0x8a, 0x94, 0x3e, 0xb6, 0xe4, 0x18, 0xc7, 0xd0, 0x2e,
	0x8b, 0x7d, 0x12, 0xed, 0xb2, 0x88, 0x56, 0x30, 0x52, 0x8d, 0x0e, 0xef, 0x61, 0xa4, 0x7a, 0x9d,
	0x09, 0xe6, 0x9d, 0x7f, 0x37, 0x79, 0x5f, 0x2f, 0xbf, 0x02, 0x40, 0xa5, 0x3e, 0x93, 0xfd, 0x2c,
	0x73, 0xc2, 0x15, 0x9c, 0xed, 0x9c, 0xea, 0xdf, 0x73, 0x74, 0xe6, 0x74, 0xe6, 0x29, 0x7e, 0x46,
	0x51, 0x0b, 0x1f, 0xe1, 0xf4, 0x89, 0xd8, 0xbb, 0x7a, 0xe2, 0x75, 0xfc, 0xba, 0x9d, 0x9e, 0x1f,
	0xdb, 0xe1, 0xa2, 0xd6, 0x6b, 0x4f, 0xde, 0xd0, 0xed, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x48,
	0xb9, 0xf7, 0x3e, 0x6a, 0x02, 0x00, 0x00,
}
