// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/transaction/transaction.proto

package transaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	TransactionID        string   `protobuf:"bytes,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`
	MerchantID           string   `protobuf:"bytes,3,opt,name=merchantID,proto3" json:"merchantID,omitempty"`
	StoreID              string   `protobuf:"bytes,4,opt,name=storeID,proto3" json:"storeID,omitempty"`
	Date                 string   `protobuf:"bytes,7,opt,name=date,proto3" json:"date,omitempty"`
	Time                 string   `protobuf:"bytes,8,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_2129939cf85d765e, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

func (m *Transaction) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *Transaction) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *Transaction) GetStoreID() string {
	if m != nil {
		return m.StoreID
	}
	return ""
}

func (m *Transaction) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *Transaction) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

// Query transactions by User, Merchant, or ID
type IDRequest struct {
	MerchantID           string   `protobuf:"bytes,1,opt,name=MerchantID,proto3" json:"MerchantID,omitempty"`
	UserID               string   `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	TransactionID        string   `protobuf:"bytes,3,opt,name=TransactionID,proto3" json:"TransactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDRequest) Reset()         { *m = IDRequest{} }
func (m *IDRequest) String() string { return proto.CompactTextString(m) }
func (*IDRequest) ProtoMessage()    {}
func (*IDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2129939cf85d765e, []int{1}
}

func (m *IDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDRequest.Unmarshal(m, b)
}
func (m *IDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDRequest.Marshal(b, m, deterministic)
}
func (m *IDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDRequest.Merge(m, src)
}
func (m *IDRequest) XXX_Size() int {
	return xxx_messageInfo_IDRequest.Size(m)
}
func (m *IDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDRequest proto.InternalMessageInfo

func (m *IDRequest) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *IDRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *IDRequest) GetTransactionID() string {
	if m != nil {
		return m.TransactionID
	}
	return ""
}

// Generic CRUD Response
type CRUDResponse struct {
	Executed             bool           `protobuf:"varint,1,opt,name=executed,proto3" json:"executed,omitempty"`
	Transactions         []*Transaction `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CRUDResponse) Reset()         { *m = CRUDResponse{} }
func (m *CRUDResponse) String() string { return proto.CompactTextString(m) }
func (*CRUDResponse) ProtoMessage()    {}
func (*CRUDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2129939cf85d765e, []int{2}
}

func (m *CRUDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CRUDResponse.Unmarshal(m, b)
}
func (m *CRUDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CRUDResponse.Marshal(b, m, deterministic)
}
func (m *CRUDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CRUDResponse.Merge(m, src)
}
func (m *CRUDResponse) XXX_Size() int {
	return xxx_messageInfo_CRUDResponse.Size(m)
}
func (m *CRUDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CRUDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CRUDResponse proto.InternalMessageInfo

func (m *CRUDResponse) GetExecuted() bool {
	if m != nil {
		return m.Executed
	}
	return false
}

func (m *CRUDResponse) GetTransactions() []*Transaction {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "transaction.Transaction")
	proto.RegisterType((*IDRequest)(nil), "transaction.IDRequest")
	proto.RegisterType((*CRUDResponse)(nil), "transaction.CRUDResponse")
}

func init() {
	proto.RegisterFile("proto/transaction/transaction.proto", fileDescriptor_2129939cf85d765e)
}

var fileDescriptor_2129939cf85d765e = []byte{
	// 310 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x92, 0xc1, 0x4e, 0xfa, 0x40,
	0x10, 0xc6, 0xff, 0x05, 0x02, 0x65, 0xca, 0x3f, 0xc6, 0x39, 0x90, 0x95, 0x83, 0x21, 0xd5, 0x03,
	0x27, 0x4c, 0xf0, 0xea, 0x8d, 0x8d, 0x66, 0x4d, 0xbc, 0xac, 0xf0, 0x00, 0xb5, 0x4c, 0x42, 0x13,
	0x69, 0x71, 0x77, 0x6b, 0x7c, 0x29, 0x9f, 0xce, 0x17, 0x30, 0xdd, 0x2a, 0xcc, 0x1e, 0xf4, 0xe0,
	0x6d, 0xbe, 0xdf, 0x37, 0x99, 0xf9, 0x76, 0x5a, 0xb8, 0xd8, 0x9b, 0xca, 0x55, 0x57, 0xce, 0x64,
	0xa5, 0xcd, 0x72, 0x57, 0x54, 0x25, 0xaf, 0xe7, 0xde, 0xc5, 0x84, 0xa1, 0xf4, 0x3d, 0x82, 0x64,
	0x75, 0xd4, 0x78, 0x09, 0xff, 0x99, 0xad, 0xa4, 0x88, 0xa6, 0xd1, 0x6c, 0xa8, 0x43, 0x88, 0x63,
	0xe8, 0xd7, 0x96, 0x8c, 0x92, 0xa2, 0xe3, 0xed, 0x2f, 0x85, 0xe7, 0x00, 0x3b, 0x32, 0xf9, 0x36,
	0x2b, 0x9d, 0x92, 0xa2, 0xeb, 0x3d, 0x46, 0x50, 0xc0, 0xc0, 0xba, 0xca, 0x90, 0x92, 0xa2, 0xe7,
	0xcd, 0x6f, 0x89, 0x08, 0xbd, 0x4d, 0xe6, 0x48, 0x0c, 0x3c, 0xf6, 0x75, 0xc3, 0x5c, 0xb1, 0x23,
	0x11, 0xb7, 0xac, 0xa9, 0xd3, 0x02, 0x86, 0x4a, 0x6a, 0x7a, 0xa9, 0xc9, 0xba, 0x66, 0xdd, 0xc3,
	0x71, 0x5d, 0x9b, 0x94, 0x91, 0x26, 0xe6, 0x3a, 0x88, 0xd9, 0xaa, 0xe6, 0x91, 0xab, 0xe0, 0x91,
	0x6d, 0xd2, 0x10, 0xa6, 0x5b, 0x18, 0x2d, 0xf5, 0x5a, 0x6a, 0xb2, 0xfb, 0xaa, 0xb4, 0x84, 0x13,
	0x88, 0xe9, 0x8d, 0xf2, 0xda, 0xd1, 0xc6, 0xef, 0x8a, 0xf5, 0x41, 0xe3, 0x0d, 0x8c, 0xd8, 0x85,
	0xac, 0xe8, 0x4c, 0xbb, 0xb3, 0x64, 0x21, 0xe6, 0xfc, 0xfa, 0x6c, 0xba, 0x0e, 0xba, 0x17, 0x1f,
	0x11, 0x20, 0x73, 0x1f, 0xc9, 0xbc, 0x16, 0x39, 0xe1, 0x3d, 0x9c, 0x2e, 0x0d, 0x65, 0x8e, 0xf8,
	0x07, 0xfa, 0x71, 0xe6, 0xe4, 0x2c, 0x70, 0x78, 0xf4, 0xf4, 0x1f, 0xde, 0xc2, 0xc9, 0x1d, 0x39,
	0xd6, 0x6e, 0x71, 0x1c, 0xf4, 0x1f, 0xae, 0xfa, 0xfb, 0x1c, 0x05, 0x28, 0xe9, 0x99, 0x82, 0x4c,
	0x7f, 0x1b, 0xf5, 0xd4, 0xf7, 0xbf, 0xe3, 0xf5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9d, 0x39,
	0x83, 0x84, 0xb5, 0x02, 0x00, 0x00,
}
