// Code generated by protoc-gen-go. DO NOT EDIT.
// source: campaign.proto

package campaign

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Campaign struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerchantID           string   `protobuf:"bytes,2,opt,name=merchantID,proto3" json:"merchantID,omitempty"`
	Rate                 string   `protobuf:"bytes,3,opt,name=rate,proto3" json:"rate,omitempty"`
	StartTimestamp       string   `protobuf:"bytes,4,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	EndTimestamp         string   `protobuf:"bytes,5,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	UserSet              []string `protobuf:"bytes,6,rep,name=userSet,proto3" json:"userSet,omitempty"`
	TransactionSet       []string `protobuf:"bytes,7,rep,name=transactionSet,proto3" json:"transactionSet,omitempty"`
	Title                string   `protobuf:"bytes,8,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	ValidFor             int32    `protobuf:"varint,10,opt,name=validFor,proto3" json:"validFor,omitempty"`
	Active               bool     `protobuf:"varint,11,opt,name=active,proto3" json:"active,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Campaign) Reset()         { *m = Campaign{} }
func (m *Campaign) String() string { return proto.CompactTextString(m) }
func (*Campaign) ProtoMessage()    {}
func (*Campaign) Descriptor() ([]byte, []int) {
	return fileDescriptor_dce769fb84410dc2, []int{0}
}

func (m *Campaign) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Campaign.Unmarshal(m, b)
}
func (m *Campaign) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Campaign.Marshal(b, m, deterministic)
}
func (m *Campaign) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Campaign.Merge(m, src)
}
func (m *Campaign) XXX_Size() int {
	return xxx_messageInfo_Campaign.Size(m)
}
func (m *Campaign) XXX_DiscardUnknown() {
	xxx_messageInfo_Campaign.DiscardUnknown(m)
}

var xxx_messageInfo_Campaign proto.InternalMessageInfo

func (m *Campaign) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Campaign) GetMerchantID() string {
	if m != nil {
		return m.MerchantID
	}
	return ""
}

func (m *Campaign) GetRate() string {
	if m != nil {
		return m.Rate
	}
	return ""
}

func (m *Campaign) GetStartTimestamp() string {
	if m != nil {
		return m.StartTimestamp
	}
	return ""
}

func (m *Campaign) GetEndTimestamp() string {
	if m != nil {
		return m.EndTimestamp
	}
	return ""
}

func (m *Campaign) GetUserSet() []string {
	if m != nil {
		return m.UserSet
	}
	return nil
}

func (m *Campaign) GetTransactionSet() []string {
	if m != nil {
		return m.TransactionSet
	}
	return nil
}

func (m *Campaign) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Campaign) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Campaign) GetValidFor() int32 {
	if m != nil {
		return m.ValidFor
	}
	return 0
}

func (m *Campaign) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func init() {
	proto.RegisterType((*Campaign)(nil), "campaign.Campaign")
}

func init() {
	proto.RegisterFile("campaign.proto", fileDescriptor_dce769fb84410dc2)
}

var fileDescriptor_dce769fb84410dc2 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xda, 0xa6, 0x9b, 0xa9, 0xe4, 0x30, 0x88, 0x0c, 0x1e, 0x64, 0xe9, 0x41, 0x72,
	0xf2, 0xe2, 0x23, 0x28, 0x82, 0xd7, 0xe8, 0x0b, 0xac, 0xd9, 0x41, 0x17, 0x9a, 0x4d, 0xd8, 0x1d,
	0xfb, 0x8c, 0x3e, 0x96, 0x64, 0x6c, 0xb5, 0xf6, 0x96, 0xef, 0xfb, 0x3f, 0x32, 0xb0, 0xd0, 0xf4,
	0x6e, 0x98, 0x5c, 0x78, 0x8f, 0x77, 0x53, 0x1a, 0x65, 0x44, 0x73, 0xe4, 0xed, 0x57, 0x09, 0xe6,
	0xe1, 0x00, 0xd8, 0x40, 0x19, 0x3c, 0x15, 0xb6, 0x68, 0xeb, 0xae, 0x0c, 0x1e, 0x6f, 0x00, 0x06,
	0x4e, 0xfd, 0x87, 0x8b, 0xf2, 0xfc, 0x48, 0xa5, 0xfa, 0x13, 0x83, 0x08, 0xcb, 0xe4, 0x84, 0x69,
	0xa1, 0x8b, 0x7e, 0xe3, 0x2d, 0x34, 0x59, 0x5c, 0x92, 0xd7, 0x30, 0x70, 0x16, 0x37, 0x4c, 0xb4,
	0xd4, 0xf5, 0xcc, 0xe2, 0x16, 0x2e, 0x38, 0xfa, 0xbf, 0x6a, 0xa5, 0xd5, 0x3f, 0x87, 0x04, 0xeb,
	0xcf, 0xcc, 0xe9, 0x85, 0x85, 0x2a, 0xbb, 0x68, 0xeb, 0xee, 0x88, 0xf3, 0x15, 0x49, 0x2e, 0x66,
	0xd7, 0x4b, 0x18, 0xe3, 0x1c, 0xac, 0x35, 0x38, 0xb3, 0x78, 0x09, 0x2b, 0x09, 0xb2, 0x63, 0x32,
	0xfa, 0xfb, 0x1f, 0x40, 0x0b, 0x1b, 0xcf, 0xb9, 0x4f, 0x61, 0x9a, 0x3b, 0xaa, 0x75, 0x3b, 0x55,
	0x78, 0x0d, 0x66, 0xef, 0x76, 0xc1, 0x3f, 0x8d, 0x89, 0xc0, 0x16, 0xed, 0xaa, 0xfb, 0x65, 0xbc,
	0x82, 0x6a, 0x3e, 0xb0, 0x67, 0xda, 0xd8, 0xa2, 0x35, 0xdd, 0x81, 0xde, 0x2a, 0x7d, 0xdb, 0xfb,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x8f, 0xe6, 0x9b, 0x6d, 0x01, 0x00, 0x00,
}
