// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/user/user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	UserID               string    `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	FirstName            string    `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string    `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Dob                  string    `protobuf:"bytes,4,opt,name=dob,proto3" json:"dob,omitempty"`
	Gender               string    `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	University           string    `protobuf:"bytes,6,opt,name=university,proto3" json:"university,omitempty"`
	Accounts             *Accounts `protobuf:"bytes,7,opt,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *User) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *User) GetUniversity() string {
	if m != nil {
		return m.University
	}
	return ""
}

func (m *User) GetAccounts() *Accounts {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type Accounts struct {
	AccountID            []string `protobuf:"bytes,1,rep,name=accountID,proto3" json:"accountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Accounts) Reset()         { *m = Accounts{} }
func (m *Accounts) String() string { return proto.CompactTextString(m) }
func (*Accounts) ProtoMessage()    {}
func (*Accounts) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{1}
}

func (m *Accounts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Accounts.Unmarshal(m, b)
}
func (m *Accounts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Accounts.Marshal(b, m, deterministic)
}
func (m *Accounts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Accounts.Merge(m, src)
}
func (m *Accounts) XXX_Size() int {
	return xxx_messageInfo_Accounts.Size(m)
}
func (m *Accounts) XXX_DiscardUnknown() {
	xxx_messageInfo_Accounts.DiscardUnknown(m)
}

var xxx_messageInfo_Accounts proto.InternalMessageInfo

func (m *Accounts) GetAccountID() []string {
	if m != nil {
		return m.AccountID
	}
	return nil
}

type CreateResponse struct {
	Created              bool     `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	User                 *User    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateResponse) Reset()         { *m = CreateResponse{} }
func (m *CreateResponse) String() string { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()    {}
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{2}
}

func (m *CreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateResponse.Unmarshal(m, b)
}
func (m *CreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateResponse.Marshal(b, m, deterministic)
}
func (m *CreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateResponse.Merge(m, src)
}
func (m *CreateResponse) XXX_Size() int {
	return xxx_messageInfo_CreateResponse.Size(m)
}
func (m *CreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateResponse proto.InternalMessageInfo

func (m *CreateResponse) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *CreateResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b283a848145d6b7, []int{4}
}

func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (m *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(m, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "user.User")
	proto.RegisterType((*Accounts)(nil), "user.Accounts")
	proto.RegisterType((*CreateResponse)(nil), "user.CreateResponse")
	proto.RegisterType((*GetRequest)(nil), "user.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "user.GetResponse")
}

func init() {
	proto.RegisterFile("proto/user/user.proto", fileDescriptor_9b283a848145d6b7)
}

var fileDescriptor_9b283a848145d6b7 = []byte{
	// 322 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x4d, 0xff, 0xa6, 0x13, 0x28, 0x75, 0x50, 0x59, 0x4a, 0x29, 0x25, 0xa7, 0xe2, 0xa1,
	0x2d, 0xf5, 0x09, 0x44, 0xa1, 0xe8, 0xc1, 0xc3, 0x8a, 0x0f, 0x90, 0x26, 0xa3, 0x2c, 0x68, 0xd2,
	0xee, 0x6e, 0x0a, 0xbe, 0xa4, 0xcf, 0x24, 0x3b, 0xbb, 0x6d, 0xd3, 0x4b, 0xd8, 0xef, 0xf7, 0xcd,
	0x66, 0x66, 0xbe, 0x04, 0x6e, 0x77, 0xba, 0xb2, 0xd5, 0xb2, 0x36, 0xa4, 0xf9, 0xb1, 0x60, 0x8d,
	0x1d, 0x77, 0x4e, 0xff, 0x22, 0xe8, 0x7c, 0x18, 0xd2, 0x78, 0x07, 0x3d, 0x07, 0x5e, 0x9e, 0x45,
	0x34, 0x8b, 0xe6, 0x03, 0x19, 0x14, 0x4e, 0x60, 0xf0, 0xa9, 0xb4, 0xb1, 0x6f, 0xd9, 0x0f, 0x89,
	0x16, 0x5b, 0x67, 0x80, 0x63, 0x88, 0xbf, 0xb3, 0x60, 0xb6, 0xd9, 0x3c, 0x69, 0x1c, 0x41, 0xbb,
	0xa8, 0xb6, 0xa2, 0xc3, 0xd8, 0x1d, 0x5d, 0x8f, 0x2f, 0x2a, 0x0b, 0xd2, 0xa2, 0xeb, 0x7b, 0x78,
	0x85, 0x53, 0x80, 0xba, 0x54, 0x07, 0xd2, 0x46, 0xd9, 0x5f, 0xd1, 0x63, 0xaf, 0x41, 0xf0, 0x1e,
	0xe2, 0x2c, 0xcf, 0xab, 0xba, 0xb4, 0x46, 0xf4, 0x67, 0xd1, 0x3c, 0x59, 0x0f, 0x17, 0xbc, 0xc9,
	0x63, 0xa0, 0xf2, 0xe4, 0xa7, 0x73, 0x88, 0x8f, 0xd4, 0xcd, 0x1e, 0x38, 0xaf, 0xd5, 0x76, 0xb3,
	0x9f, 0x40, 0xfa, 0x0a, 0xc3, 0x27, 0x4d, 0x99, 0x25, 0x49, 0x66, 0x57, 0x95, 0x86, 0x50, 0x40,
	0x3f, 0x67, 0x52, 0x70, 0x08, 0xb1, 0x3c, 0x4a, 0x9c, 0x02, 0xc7, 0xc5, 0x01, 0x24, 0x6b, 0xf0,
	0xdd, 0x5d, 0x6e, 0xd2, 0xc7, 0x38, 0x01, 0xd8, 0x90, 0x95, 0xb4, 0xaf, 0xc9, 0x58, 0x1c, 0x42,
	0x4b, 0x15, 0x21, 0xc7, 0x96, 0x2a, 0xd2, 0x25, 0x24, 0xec, 0x86, 0x36, 0x33, 0xe8, 0xba, 0x4b,
	0x86, 0x47, 0xba, 0x7c, 0x9b, 0x37, 0xd6, 0x7b, 0x48, 0x9c, 0x7c, 0x27, 0x7d, 0x50, 0x39, 0xe1,
	0x0a, 0xc0, 0x4f, 0xca, 0x5f, 0xaa, 0x51, 0x3f, 0xbe, 0xf1, 0xe7, 0xcb, 0x3d, 0xd2, 0x2b, 0x5c,
	0x41, 0x7f, 0x43, 0x96, 0xcb, 0x47, 0xbe, 0xe4, 0x3c, 0xde, 0xf8, 0xba, 0x41, 0x8e, 0x37, 0xb6,
	0x3d, 0xfe, 0x2b, 0x1e, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xeb, 0x13, 0xf5, 0x2e, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for UserService service

type UserServiceClient interface {
	CreateUser(ctx context.Context, in *User, opts ...client.CallOption) (*CreateResponse, error)
	GetUser(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
}

type userServiceClient struct {
	c           client.Client
	serviceName string
}

func NewUserServiceClient(serviceName string, c client.Client) UserServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "user"
	}
	return &userServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *User, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.CreateUser", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.serviceName, "UserService.GetUser", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for UserService service

type UserServiceHandler interface {
	CreateUser(context.Context, *User, *CreateResponse) error
	GetUser(context.Context, *GetRequest, *GetResponse) error
}

func RegisterUserServiceHandler(s server.Server, hdlr UserServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&UserService{hdlr}, opts...))
}

type UserService struct {
	UserServiceHandler
}

func (h *UserService) CreateUser(ctx context.Context, in *User, out *CreateResponse) error {
	return h.UserServiceHandler.CreateUser(ctx, in, out)
}

func (h *UserService) GetUser(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.UserServiceHandler.GetUser(ctx, in, out)
}
