// Code generated by protoc-gen-go. DO NOT EDIT.
// source: partner-merchant.proto

package partnermerchant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PartnerMerchant struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Locations            []string `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	ApiTags              []string `protobuf:"bytes,4,rep,name=api_tags,json=apiTags,proto3" json:"api_tags,omitempty"`
	OtisTags             []string `protobuf:"bytes,5,rep,name=otis_tags,json=otisTags,proto3" json:"otis_tags,omitempty"`
	Sector               string   `protobuf:"bytes,6,opt,name=sector,proto3" json:"sector,omitempty"`
	Size                 string   `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	Rate                 int32    `protobuf:"varint,8,opt,name=rate,proto3" json:"rate,omitempty"`
	JoinDate             string   `protobuf:"bytes,9,opt,name=joinDate,proto3" json:"joinDate,omitempty"`
	NextBillingDate      string   `protobuf:"bytes,10,opt,name=nextBillingDate,proto3" json:"nextBillingDate,omitempty"`
	GocardlessMandate    string   `protobuf:"bytes,11,opt,name=gocardlessMandate,proto3" json:"gocardlessMandate,omitempty"`
	ExpenseBand          string   `protobuf:"bytes,12,opt,name=expenseBand,proto3" json:"expenseBand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartnerMerchant) Reset()         { *m = PartnerMerchant{} }
func (m *PartnerMerchant) String() string { return proto.CompactTextString(m) }
func (*PartnerMerchant) ProtoMessage()    {}
func (*PartnerMerchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_087e21205eb8b882, []int{0}
}

func (m *PartnerMerchant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartnerMerchant.Unmarshal(m, b)
}
func (m *PartnerMerchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartnerMerchant.Marshal(b, m, deterministic)
}
func (m *PartnerMerchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartnerMerchant.Merge(m, src)
}
func (m *PartnerMerchant) XXX_Size() int {
	return xxx_messageInfo_PartnerMerchant.Size(m)
}
func (m *PartnerMerchant) XXX_DiscardUnknown() {
	xxx_messageInfo_PartnerMerchant.DiscardUnknown(m)
}

var xxx_messageInfo_PartnerMerchant proto.InternalMessageInfo

func (m *PartnerMerchant) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PartnerMerchant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PartnerMerchant) GetLocations() []string {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *PartnerMerchant) GetApiTags() []string {
	if m != nil {
		return m.ApiTags
	}
	return nil
}

func (m *PartnerMerchant) GetOtisTags() []string {
	if m != nil {
		return m.OtisTags
	}
	return nil
}

func (m *PartnerMerchant) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

func (m *PartnerMerchant) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *PartnerMerchant) GetRate() int32 {
	if m != nil {
		return m.Rate
	}
	return 0
}

func (m *PartnerMerchant) GetJoinDate() string {
	if m != nil {
		return m.JoinDate
	}
	return ""
}

func (m *PartnerMerchant) GetNextBillingDate() string {
	if m != nil {
		return m.NextBillingDate
	}
	return ""
}

func (m *PartnerMerchant) GetGocardlessMandate() string {
	if m != nil {
		return m.GocardlessMandate
	}
	return ""
}

func (m *PartnerMerchant) GetExpenseBand() string {
	if m != nil {
		return m.ExpenseBand
	}
	return ""
}

func init() {
	proto.RegisterType((*PartnerMerchant)(nil), "partnermerchant.PartnerMerchant")
}

func init() {
	proto.RegisterFile("partner-merchant.proto", fileDescriptor_087e21205eb8b882)
}

var fileDescriptor_087e21205eb8b882 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0xd0, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x07, 0x70, 0x92, 0xb6, 0x69, 0x32, 0x15, 0x83, 0x73, 0x28, 0xeb, 0xc7, 0x21, 0x78, 0xca,
	0x41, 0xbd, 0xf8, 0x06, 0xc5, 0x6b, 0x41, 0x82, 0x77, 0x19, 0x93, 0x21, 0xae, 0xa4, 0xbb, 0x61,
	0x77, 0x0f, 0xc5, 0xb7, 0xf5, 0x4d, 0x64, 0x27, 0xf1, 0x03, 0xbd, 0xcd, 0xfc, 0xfe, 0x7f, 0xd8,
	0x61, 0x61, 0x3b, 0x92, 0x0b, 0x86, 0xdd, 0xed, 0x81, 0x5d, 0xfb, 0x4a, 0x26, 0xdc, 0x8d, 0xce,
	0x06, 0x8b, 0xe5, 0xec, 0x5f, 0x7c, 0xfd, 0x91, 0x42, 0xf9, 0x38, 0xd9, 0x7e, 0x36, 0x3c, 0x85,
	0x54, 0x77, 0x2a, 0xa9, 0x92, 0xba, 0x68, 0x52, 0xdd, 0x21, 0xc2, 0xd2, 0xd0, 0x81, 0x55, 0x2a,
	0x22, 0x33, 0x5e, 0x41, 0x31, 0xd8, 0x96, 0x82, 0xb6, 0xc6, 0xab, 0x45, 0xb5, 0xa8, 0x8b, 0xe6,
	0x07, 0xf0, 0x1c, 0x72, 0x1a, 0xf5, 0x73, 0xa0, 0xde, 0xab, 0xa5, 0x84, 0x6b, 0x1a, 0xf5, 0x13,
	0xf5, 0x1e, 0x2f, 0xa1, 0xb0, 0x41, 0xfb, 0x29, 0x5b, 0x49, 0x96, 0x47, 0x90, 0x70, 0x0b, 0x99,
	0xe7, 0x36, 0x58, 0xa7, 0x32, 0x79, 0x6b, 0xde, 0xe2, 0x05, 0x5e, 0xbf, 0xb3, 0x5a, 0x4f, 0x17,
	0xc4, 0x39, 0x9a, 0xa3, 0xc0, 0x2a, 0xaf, 0x92, 0x7a, 0xd5, 0xc8, 0x8c, 0x17, 0x90, 0xbf, 0x59,
	0x6d, 0x1e, 0xa2, 0x17, 0xd2, 0xfd, 0xde, 0xb1, 0x86, 0xd2, 0xf0, 0x31, 0xec, 0xf4, 0x30, 0x68,
	0xd3, 0x4b, 0x05, 0xa4, 0xf2, 0x97, 0xf1, 0x06, 0xce, 0x7a, 0xdb, 0x92, 0xeb, 0x06, 0xf6, 0x7e,
	0x4f, 0xa6, 0x8b, 0xdd, 0x8d, 0x74, 0xff, 0x07, 0x58, 0xc1, 0x86, 0x8f, 0x23, 0x1b, 0xcf, 0x3b,
	0x32, 0x9d, 0x3a, 0x91, 0xde, 0x6f, 0x7a, 0xc9, 0xe4, 0xef, 0xef, 0x3f, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x09, 0x3c, 0x88, 0x65, 0x95, 0x01, 0x00, 0x00,
}
