apiVersion: apps/v1
kind: Deployment
metadata:
  name: merchant-service
  labels:
    app: merchant-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: merchant-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: merchant-service
    spec:
      containers:
        - name: merchant-service
          image: registry.gitlab.com/otis-team/backend/service/merchant:latest
          ports:
            - containerPort: 8080
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 8080
#            initialDelaySeconds: 2
#            periodSeconds: 2
#          readinessProbe:
#            httpGet:
#              path: /healthz
#              port: 8080
#            initialDelaySeconds: 2
#            periodSeconds: 2