apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: merchant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merchant
  template:
    metadata:
      labels:
        app: merchant
    spec:
      containers:
        - name: merchant-service
          image: