# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dtypes/generalmerchant/proto/generalmerchant.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dtypes/generalmerchant/proto/generalmerchant.proto',
  package='generalmerchant',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n2dtypes/generalmerchant/proto/generalmerchant.proto\x12\x0fgeneralmerchant\"\x98\x01\n\x0fGeneralMerchant\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\tlocations\x18\x03 \x03(\t\x12\x10\n\x08\x61pi_tags\x18\x04 \x03(\t\x12\x13\n\x0bscrape_tags\x18\x05 \x03(\t\x12\x0e\n\x06sector\x18\x06 \x01(\t\x12\x0c\n\x04size\x18\x07 \x01(\t\x12\x13\n\x0b\x65xpenseBand\x18\x0c \x01(\tb\x06proto3'
)




_GENERALMERCHANT = _descriptor.Descriptor(
  name='GeneralMerchant',
  full_name='generalmerchant.GeneralMerchant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='generalmerchant.GeneralMerchant.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='generalmerchant.GeneralMerchant.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='locations', full_name='generalmerchant.GeneralMerchant.locations', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='api_tags', full_name='generalmerchant.GeneralMerchant.api_tags', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scrape_tags', full_name='generalmerchant.GeneralMerchant.scrape_tags', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sector', full_name='generalmerchant.GeneralMerchant.sector', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='generalmerchant.GeneralMerchant.size', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='expenseBand', full_name='generalmerchant.GeneralMerchant.expenseBand', index=7,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=224,
)

DESCRIPTOR.message_types_by_name['GeneralMerchant'] = _GENERALMERCHANT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GeneralMerchant = _reflection.GeneratedProtocolMessageType('GeneralMerchant', (_message.Message,), {
  'DESCRIPTOR' : _GENERALMERCHANT,
  '__module__' : 'dtypes.generalmerchant.proto.generalmerchant_pb2'
  # @@protoc_insertion_point(class_scope:generalmerchant.GeneralMerchant)
  })
_sym_db.RegisterMessage(GeneralMerchant)


# @@protoc_insertion_point(module_scope)
