// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User_Gender int32

const (
	User_MALE   User_Gender = 0
	User_FEMALE User_Gender = 1
	User_OTHER  User_Gender = 2
)

var User_Gender_name = map[int32]string{
	0: "MALE",
	1: "FEMALE",
	2: "OTHER",
}

var User_Gender_value = map[string]int32{
	"MALE":   0,
	"FEMALE": 1,
	"OTHER":  2,
}

func (x User_Gender) String() string {
	return proto.EnumName(User_Gender_name, int32(x))
}

func (User_Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0, 0}
}

type User struct {
	Id                   string      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Dob                  string      `protobuf:"bytes,2,opt,name=Dob,proto3" json:"Dob,omitempty"`
	Gender               User_Gender `protobuf:"varint,3,opt,name=gender,proto3,enum=user.User_Gender" json:"gender,omitempty"`
	GenderDescription    string      `protobuf:"bytes,4,opt,name=genderDescription,proto3" json:"genderDescription,omitempty"`
	University           string      `protobuf:"bytes,5,opt,name=university,proto3" json:"university,omitempty"`
	JoinDate             string      `protobuf:"bytes,6,opt,name=joinDate,proto3" json:"joinDate,omitempty"`
	GraduationYear       string      `protobuf:"bytes,7,opt,name=graduationYear,proto3" json:"graduationYear,omitempty"`
	AverageWeeklySpend   float64     `protobuf:"fixed64,8,opt,name=averageWeeklySpend,proto3" json:"averageWeeklySpend,omitempty"`
	Nationality          string      `protobuf:"bytes,9,opt,name=nationality,proto3" json:"nationality,omitempty"`
	Tags                 []string    `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetDob() string {
	if m != nil {
		return m.Dob
	}
	return ""
}

func (m *User) GetGender() User_Gender {
	if m != nil {
		return m.Gender
	}
	return User_MALE
}

func (m *User) GetGenderDescription() string {
	if m != nil {
		return m.GenderDescription
	}
	return ""
}

func (m *User) GetUniversity() string {
	if m != nil {
		return m.University
	}
	return ""
}

func (m *User) GetJoinDate() string {
	if m != nil {
		return m.JoinDate
	}
	return ""
}

func (m *User) GetGraduationYear() string {
	if m != nil {
		return m.GraduationYear
	}
	return ""
}

func (m *User) GetAverageWeeklySpend() float64 {
	if m != nil {
		return m.AverageWeeklySpend
	}
	return 0
}

func (m *User) GetNationality() string {
	if m != nil {
		return m.Nationality
	}
	return ""
}

func (m *User) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func init() {
	proto.RegisterEnum("user.User_Gender", User_Gender_name, User_Gender_value)
	proto.RegisterType((*User)(nil), "user.User")
}

func init() {
	proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf)
}

var fileDescriptor_116e343673f7ffaf = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x4d, 0xdb, 0xd5, 0xf6, 0x09, 0xa5, 0x7b, 0xa7, 0xe0, 0x41, 0xca, 0x0e, 0xd2, 0x81,
	0xf4, 0xa0, 0x7f, 0x81, 0xd0, 0xaa, 0x07, 0x45, 0xa8, 0x8a, 0x78, 0xcc, 0xec, 0xa3, 0x44, 0x47,
	0x5a, 0xd2, 0x76, 0xb0, 0x7f, 0xdc, 0xb3, 0xe4, 0x4d, 0x64, 0xe8, 0x6e, 0x9f, 0x7c, 0x7f, 0x11,
	0x12, 0x80, 0x69, 0x20, 0x5b, 0xf4, 0xb6, 0x1b, 0x3b, 0x0c, 0x1c, 0x2f, 0xbe, 0x3c, 0x08, 0x5e,
	0x06, 0xb2, 0x98, 0x80, 0xa7, 0x1b, 0x29, 0x32, 0x91, 0xc7, 0xb5, 0xa7, 0x1b, 0x4c, 0xc1, 0x2f,
	0xbb, 0x95, 0xf4, 0x58, 0x70, 0x88, 0x4b, 0x08, 0x5b, 0x32, 0x0d, 0x59, 0xe9, 0x67, 0x22, 0x4f,
	0x2e, 0xe7, 0x05, 0xaf, 0xb9, 0x76, 0x71, 0xcb, 0x46, 0xfd, 0x13, 0xc0, 0x0b, 0x98, 0xef, 0xa8,
	0xa4, 0xe1, 0xdd, 0xea, 0x7e, 0xd4, 0x9d, 0x91, 0x01, 0x4f, 0xfd, 0x37, 0xf0, 0x0c, 0x60, 0x32,
	0x7a, 0x43, 0x76, 0xd0, 0xe3, 0x56, 0xce, 0x38, 0xb6, 0xa7, 0xe0, 0x29, 0x44, 0x1f, 0x9d, 0x36,
	0xa5, 0x1a, 0x49, 0x86, 0xec, 0xfe, 0x9e, 0xf1, 0x1c, 0x92, 0xd6, 0xaa, 0x66, 0x52, 0x6e, 0xe9,
	0x8d, 0x94, 0x95, 0xc7, 0x9c, 0xf8, 0xa3, 0x62, 0x01, 0xa8, 0x36, 0x64, 0x55, 0x4b, 0xaf, 0x44,
	0x9f, 0xeb, 0xed, 0x53, 0x4f, 0xa6, 0x91, 0x51, 0x26, 0x72, 0x51, 0x1f, 0x70, 0x30, 0x83, 0x13,
	0xc3, 0x6d, 0xb5, 0x76, 0x97, 0x8a, 0x79, 0x74, 0x5f, 0x42, 0x84, 0x60, 0x54, 0xed, 0x20, 0x21,
	0xf3, 0xf3, 0xb8, 0x66, 0x5e, 0x2c, 0x21, 0xdc, 0xbd, 0x04, 0x46, 0x10, 0x3c, 0x5c, 0xdf, 0x57,
	0xe9, 0x11, 0x02, 0x84, 0x37, 0x15, 0xb3, 0xc0, 0x18, 0x66, 0x8f, 0xcf, 0x77, 0x55, 0x9d, 0x7a,
	0xab, 0x90, 0x7f, 0xe1, 0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x58, 0x52, 0x94, 0xbd, 0x93, 0x01,
	0x00, 0x00,
}
