# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/merchant/merchant.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dtypes.partnermerchant.proto import partnermerchant_pb2 as dtypes_dot_partnermerchant_dot_proto_dot_partnermerchant__pb2
from dtypes.generalmerchant.proto import generalmerchant_pb2 as dtypes_dot_generalmerchant_dot_proto_dot_generalmerchant__pb2

DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/merchant/merchant.proto',
  package='merchant',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x1dproto/merchant/merchant.proto\x12\x08merchant\x1a\x32\x64types/partnermerchant/proto/partnermerchant.proto\x1a\x32\x64types/generalmerchant/proto/generalmerchant.proto\"#\n\rMerchantQuery\x12\x12\n\nmerchantID\x18\x01 \x01(\t\"\x87\x01\n\x0fMerchantRequest\x12\x39\n\x0fpartnerMerchant\x18\x01 \x01(\x0b\x32 .partnermerchant.PartnerMerchant\x12\x39\n\x0fgeneralMerchant\x18\x02 \x01(\x0b\x32 .generalmerchant.GeneralMerchant\"\x9d\x01\n\x11MerchantsResponse\x12\x10\n\x08\x65xecuted\x18\x01 \x01(\x08\x12:\n\x10partnerMerchants\x18\x02 \x03(\x0b\x32 .partnermerchant.PartnerMerchant\x12:\n\x10generalMerchants\x18\x03 \x03(\x0b\x32 .generalmerchant.GeneralMerchant2\xf5\x03\n\x0fMerchantService\x12Q\n\x15\x43reateGeneralMerchant\x12\x19.merchant.MerchantRequest\x1a\x1b.merchant.MerchantsResponse\"\x00\x12Q\n\x15\x43reatePartnerMerchant\x12\x19.merchant.MerchantRequest\x1a\x1b.merchant.MerchantsResponse\"\x00\x12L\n\x12GetGeneralMerchant\x12\x17.merchant.MerchantQuery\x1a\x1b.merchant.MerchantsResponse\"\x00\x12L\n\x12GetPartnerMerchant\x12\x17.merchant.MerchantQuery\x1a\x1b.merchant.MerchantsResponse\"\x00\x12O\n\x15\x44\x65leteGeneralMerchant\x12\x17.merchant.MerchantQuery\x1a\x1b.merchant.MerchantsResponse\"\x00\x12O\n\x15\x44\x65letePartnerMerchant\x12\x17.merchant.MerchantQuery\x1a\x1b.merchant.MerchantsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[dtypes_dot_partnermerchant_dot_proto_dot_partnermerchant__pb2.DESCRIPTOR,dtypes_dot_generalmerchant_dot_proto_dot_generalmerchant__pb2.DESCRIPTOR,])




_MERCHANTQUERY = _descriptor.Descriptor(
  name='MerchantQuery',
  full_name='merchant.MerchantQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='merchantID', full_name='merchant.MerchantQuery.merchantID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=182,
)


_MERCHANTREQUEST = _descriptor.Descriptor(
  name='MerchantRequest',
  full_name='merchant.MerchantRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='partnerMerchant', full_name='merchant.MerchantRequest.partnerMerchant', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generalMerchant', full_name='merchant.MerchantRequest.generalMerchant', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=185,
  serialized_end=320,
)


_MERCHANTSRESPONSE = _descriptor.Descriptor(
  name='MerchantsResponse',
  full_name='merchant.MerchantsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='executed', full_name='merchant.MerchantsResponse.executed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='partnerMerchants', full_name='merchant.MerchantsResponse.partnerMerchants', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generalMerchants', full_name='merchant.MerchantsResponse.generalMerchants', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=480,
)

_MERCHANTREQUEST.fields_by_name['partnerMerchant'].message_type = dtypes_dot_partnermerchant_dot_proto_dot_partnermerchant__pb2._PARTNERMERCHANT
_MERCHANTREQUEST.fields_by_name['generalMerchant'].message_type = dtypes_dot_generalmerchant_dot_proto_dot_generalmerchant__pb2._GENERALMERCHANT
_MERCHANTSRESPONSE.fields_by_name['partnerMerchants'].message_type = dtypes_dot_partnermerchant_dot_proto_dot_partnermerchant__pb2._PARTNERMERCHANT
_MERCHANTSRESPONSE.fields_by_name['generalMerchants'].message_type = dtypes_dot_generalmerchant_dot_proto_dot_generalmerchant__pb2._GENERALMERCHANT
DESCRIPTOR.message_types_by_name['MerchantQuery'] = _MERCHANTQUERY
DESCRIPTOR.message_types_by_name['MerchantRequest'] = _MERCHANTREQUEST
DESCRIPTOR.message_types_by_name['MerchantsResponse'] = _MERCHANTSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MerchantQuery = _reflection.GeneratedProtocolMessageType('MerchantQuery', (_message.Message,), {
  'DESCRIPTOR' : _MERCHANTQUERY,
  '__module__' : 'proto.merchant.merchant_pb2'
  # @@protoc_insertion_point(class_scope:merchant.MerchantQuery)
  })
_sym_db.RegisterMessage(MerchantQuery)

MerchantRequest = _reflection.GeneratedProtocolMessageType('MerchantRequest', (_message.Message,), {
  'DESCRIPTOR' : _MERCHANTREQUEST,
  '__module__' : 'proto.merchant.merchant_pb2'
  # @@protoc_insertion_point(class_scope:merchant.MerchantRequest)
  })
_sym_db.RegisterMessage(MerchantRequest)

MerchantsResponse = _reflection.GeneratedProtocolMessageType('MerchantsResponse', (_message.Message,), {
  'DESCRIPTOR' : _MERCHANTSRESPONSE,
  '__module__' : 'proto.merchant.merchant_pb2'
  # @@protoc_insertion_point(class_scope:merchant.MerchantsResponse)
  })
_sym_db.RegisterMessage(MerchantsResponse)



_MERCHANTSERVICE = _descriptor.ServiceDescriptor(
  name='MerchantService',
  full_name='merchant.MerchantService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=483,
  serialized_end=984,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateGeneralMerchant',
    full_name='merchant.MerchantService.CreateGeneralMerchant',
    index=0,
    containing_service=None,
    input_type=_MERCHANTREQUEST,
    output_type=_MERCHANTSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CreatePartnerMerchant',
    full_name='merchant.MerchantService.CreatePartnerMerchant',
    index=1,
    containing_service=None,
    input_type=_MERCHANTREQUEST,
    output_type=_MERCHANTSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetGeneralMerchant',
    full_name='merchant.MerchantService.GetGeneralMerchant',
    index=2,
    containing_service=None,
    input_type=_MERCHANTQUERY,
    output_type=_MERCHANTSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPartnerMerchant',
    full_name='merchant.MerchantService.GetPartnerMerchant',
    index=3,
    containing_service=None,
    input_type=_MERCHANTQUERY,
    output_type=_MERCHANTSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteGeneralMerchant',
    full_name='merchant.MerchantService.DeleteGeneralMerchant',
    index=4,
    containing_service=None,
    input_type=_MERCHANTQUERY,
    output_type=_MERCHANTSRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DeletePartnerMerchant',
    full_name='merchant.MerchantService.DeletePartnerMerchant',
    index=5,
    containing_service=None,
    input_type=_MERCHANTQUERY,
    output_type=_MERCHANTSRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MERCHANTSERVICE)

DESCRIPTOR.services_by_name['MerchantService'] = _MERCHANTSERVICE

# @@protoc_insertion_point(module_scope)
