// Code generated by protoc-gen-go. DO NOT EDIT.
// source: general-merchant.proto

package generalmerchant

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GeneralMerchant struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Locations            []string `protobuf:"bytes,3,rep,name=locations,proto3" json:"locations,omitempty"`
	ApiTags              []string `protobuf:"bytes,4,rep,name=api_tags,json=apiTags,proto3" json:"api_tags,omitempty"`
	ScrapeTags           []string `protobuf:"bytes,5,rep,name=scrape_tags,json=scrapeTags,proto3" json:"scrape_tags,omitempty"`
	Sector               string   `protobuf:"bytes,6,opt,name=sector,proto3" json:"sector,omitempty"`
	Size                 string   `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	ExpenseBand          string   `protobuf:"bytes,12,opt,name=expenseBand,proto3" json:"expenseBand,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralMerchant) Reset()         { *m = GeneralMerchant{} }
func (m *GeneralMerchant) String() string { return proto.CompactTextString(m) }
func (*GeneralMerchant) ProtoMessage()    {}
func (*GeneralMerchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef294ce857877ea4, []int{0}
}

func (m *GeneralMerchant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralMerchant.Unmarshal(m, b)
}
func (m *GeneralMerchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralMerchant.Marshal(b, m, deterministic)
}
func (m *GeneralMerchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralMerchant.Merge(m, src)
}
func (m *GeneralMerchant) XXX_Size() int {
	return xxx_messageInfo_GeneralMerchant.Size(m)
}
func (m *GeneralMerchant) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralMerchant.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralMerchant proto.InternalMessageInfo

func (m *GeneralMerchant) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GeneralMerchant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GeneralMerchant) GetLocations() []string {
	if m != nil {
		return m.Locations
	}
	return nil
}

func (m *GeneralMerchant) GetApiTags() []string {
	if m != nil {
		return m.ApiTags
	}
	return nil
}

func (m *GeneralMerchant) GetScrapeTags() []string {
	if m != nil {
		return m.ScrapeTags
	}
	return nil
}

func (m *GeneralMerchant) GetSector() string {
	if m != nil {
		return m.Sector
	}
	return ""
}

func (m *GeneralMerchant) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *GeneralMerchant) GetExpenseBand() string {
	if m != nil {
		return m.ExpenseBand
	}
	return ""
}

func init() {
	proto.RegisterType((*GeneralMerchant)(nil), "generalmerchant.GeneralMerchant")
}

func init() {
	proto.RegisterFile("general-merchant.proto", fileDescriptor_ef294ce857877ea4)
}

var fileDescriptor_ef294ce857877ea4 = []byte{
	// 206 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcf, 0x31, 0x4b, 0xc5, 0x30,
	0x10, 0xc0, 0x71, 0xda, 0xf7, 0xec, 0xb3, 0x57, 0xb1, 0x70, 0x43, 0x89, 0x20, 0x58, 0x9c, 0xba,
	0xe8, 0xe2, 0x37, 0x70, 0x71, 0x72, 0x29, 0xee, 0x72, 0xa6, 0x47, 0x0d, 0xb4, 0x49, 0x48, 0x32,
	0x88, 0xdf, 0xd5, 0xef, 0x22, 0xbd, 0x54, 0x7c, 0xdb, 0xe5, 0xf7, 0x0f, 0xe4, 0x02, 0xdd, 0xcc,
	0x96, 0x03, 0x2d, 0x0f, 0x2b, 0x07, 0xfd, 0x49, 0x36, 0x3d, 0xfa, 0xe0, 0x92, 0xc3, 0x76, 0xf7,
	0x3f, 0xbe, 0xff, 0x29, 0xa0, 0x7d, 0xc9, 0xf6, 0xba, 0x1b, 0x5e, 0x43, 0x69, 0x26, 0x55, 0xf4,
	0xc5, 0x50, 0x8f, 0xa5, 0x99, 0x10, 0xe1, 0x68, 0x69, 0x65, 0x55, 0x8a, 0xc8, 0x8c, 0xb7, 0x50,
	0x2f, 0x4e, 0x53, 0x32, 0xce, 0x46, 0x75, 0xe8, 0x0f, 0x43, 0x3d, 0xfe, 0x03, 0xde, 0xc0, 0x25,
	0x79, 0xf3, 0x9e, 0x68, 0x8e, 0xea, 0x28, 0xf1, 0x44, 0xde, 0xbc, 0xd1, 0x1c, 0xf1, 0x0e, 0x9a,
	0xa8, 0x03, 0x79, 0xce, 0xf5, 0x42, 0x2a, 0x64, 0x92, 0x0b, 0x1d, 0x54, 0x91, 0x75, 0x72, 0x41,
	0x55, 0xf2, 0xde, 0x7e, 0xda, 0xb6, 0x88, 0xe6, 0x9b, 0xd5, 0x29, 0x6f, 0xb1, 0xcd, 0xd8, 0x43,
	0xc3, 0x5f, 0x9e, 0x6d, 0xe4, 0x67, 0xb2, 0x93, 0xba, 0x92, 0x74, 0x4e, 0x1f, 0x95, 0xfc, 0xfb,
	0xe9, 0x37, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x8b, 0xcf, 0x56, 0x11, 0x01, 0x00, 0x00,
}
